### PR TITLE
Add 'SCHEMA_ENDPOINT' option

### PR DESCRIPTION
**Pull request by nckpark**
Add 'SCHEMA_ENDPOINT' option, allowing resource schema to be returned from an API endpoint. Defaults to None.

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Interesting. Care to elaborate on the use cases that might take advantage from this feature? Looks similar to what #574 would like to achieve, but with Swagger support.

**Comment by nckpark** [comment]
I'm not familiar with Swagger, but at first glance - yeah, I think the inspiration is similar, and this feature could be evolved to offer Swagger spec data as a schema format option.

My immediate use case for this is to allow an API client library to fetch and parse schema to support automatically resolving data_relations and other schema constructs and construct empty documents, all without having to maintain duplicate field and type information in the library itself.

**Comment by nckpark** [comment]
What are your thoughts on this? Any more questions?

**Comment by nicolaiarocci** [comment]
I am a little reluctant to adding this. [Eve-docs](https://github.com/charlesflynn/eve-docs) already provides insights on schema definitions and, besides that, proper Swagger support would provide a better, standardised and widely adopted solution.

**Comment by nicolaiarocci** [comment]
PS: look at the JSON-output section of the Eve-Docs readme.

**Comment by nckpark** [comment]
Eve-docs does provide schema insight - more than I thought in fact - but it doesn't fully cover my use case because it doesn't provide any schema for read only resources. (Which a schema aware client needs to still allow users to interact with fetched data, even if they can't save it.)

As for Swagger, I don't see this as an only one or the other situation. Swagger support can be added in addition to a raw schema option. The benefits of offering both:
- Developers not building or using Swagger clients have a method to access schema data as needed, without the overhead of Swagger specification parsing and translation.
- Complex schema or validation rules which don't map well to the Swagger spec format can still be provided via the API
- Validation and any other schema processing code can be shared between client and server
- Returning raw schema is simple, and already done : )

All of that being said - it's your call. If you prefer not to include this in Eve, I understand, and it's simple enough for developers to implement at the application level.

**Comment by nicolaiarocci** [comment]
Sounds good to me. I'll merge as soon as 0.6 is out of the way though.

**Comment by nckpark** [comment]
Thanks! When is the 0.6 release planned?

**Comment by nicolaiarocci** [comment]
The plan is Soon (next week, I hope). There's currently one issue with Cerberus and Python 2.6 holding it  down #701.

**Comment by nckpark** [comment]
Sounds good. We currently use an internal fork of Eve to run stable development versions, but are hoping to move back to official releases as soon as we can. What do you think the timeframe is before this SCHEMA_ENDPOINT feature makes it into an official release?

**Comment by nicolaiarocci** [comment]
Aww screw it I'm just gonna merge for 0.6 :smile:

**Comment by nckpark** [comment]
Thanks!  : D

**Comment by nicolaiarocci** [comment]
Merged in https://github.com/nicolaiarocci/eve/commit/21ac82b55e599d42c385f3933bbf3323ea37133b

**Pull request closed without merging**
