### PR TITLE
Added option to use a different authorization database.

### PR DESCRIPTION
**Pull request by Expi1**
Hi,

I added a new configuration value, `MONGO_AUTHDBNAME`, that is passed to [PyMongo's authenticate function](http://api.mongodb.org/python/current/examples/authentication.html#delegated-authentication) and should allow for authentication on databases different from the main database that's used for the data storage.

I've added it to the documentation, but unfortunately was unable to find where it should be included in the tests, however, all the tests that are existing, run fine with no issues. I'd appreciate some pointers to where tests should be included for this.

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Hello and thanks for your contribution. 

Delegated Authentication was introduced in MongoDB 2.4 and [removed on 2.6](http://api.mongodb.org/python/current/examples/authentication.html#delegated-authentication). With the advent of MongoDB 3.0 I wonder if we want to add support for this feature, given that it has been abandoned for a while. 

Thoughts?

**Comment by Expi1** [comment]
Hi,

I never noticed that feature had been removed. 

I made this change because I had been creating a docker image for an API using Eve, and was attempting to link it with the `tutum/mongodb` image by [the folks over at tutum.co](http://tutum.co). I was getting an authentication error, when I asked the developers behind the `tutum/mongodb` image I was informed that I'd have to authenticate against the `admin` database first. 

After some research, I made this change to allow for alternate authentication databases, however, I might be referring to the wrong feature when I mention Delegated Authentication - because I'm certain that the database image I'm using is version 3.0 of MongoDB, and requires me to auth on a different database. I wonder if [this mongo shell parameter](http://docs.mongodb.org/manual/reference/program/mongorestore/#cmdoption--authenticationDatabase) refers to the removed Delegated Authentication feature or something else?

**Comment by nicolaiarocci** [comment]
That link is about `mongorestore` but yes, even the [Mongo 3.0 docs](http://docs.mongodb.org/manual/reference/program/mongo/#cmdoption--authenticationDatabase) don't mention the feature as being deprecated/retired since 2.6. Also, PyMongo [changelog](http://api.mongodb.org/python/current/changelog.html) does not seem to report any significant change to authentication delegation since PyMongo 2.5 which introduced it.

Let's assume that's an error in PyMongo documentation. When I get back I will see if I can somehow add a test for this. Stay tuned.

**Comment by Expi1** [comment]
Hi,

Any update on this?

**Comment by nicolaiarocci** [comment]
Merged with https://github.com/nicolaiarocci/eve/commit/235c66f488f6b4579bc2b473187673913cd80682

Thanks!

**Pull request closed without merging**
