### PR TITLE
Fix typo in document embedding limitations example

### PR DESCRIPTION
**Pull request by pdecat**

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Hello and thanks for this. I'm willing to merge but your branch has something wrong. It only has the docs folder as root, so when merging I end up with all docs files in eve's root folder. Could you please check it and resubmit?

**Comment by pdecat** [comment]
Hi Nicola,

the branch I created using online editing was made from nicolaiarocci:gh-pages which also have the same layout as mine.

I believe I'll have to propose a second edit for fixing the docs in the develop branch.

**Comment by pdecat** [comment]
Second pull request created https://github.com/nicolaiarocci/eve/pull/782

**Comment by nicolaiarocci** [comment]
I did not notice that you wanted to merge to gh-pages. Yes you'd want to PR against develop so changes are persisted (gh-pages is just a build branch for github pages)

**Pull request closed without merging**
