### PR TITLE
Log Exception using app.logger.exception()

### PR DESCRIPTION
**Pull request by sebest**

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Thanks for this. Indeed internal app logging is needed, and it is on the roadmap probably around v0.7. I'm putting this on on hold for the time being as I first want to figure out the general design for logging (i.e. we probably want a single logging function, accessible by all exception handles *and* user functions, etc.)

**Comment by rs** [comment]
Could we have at least that in the meantime? Because as of today, it’s impossible to figure out bugs happening in production or even debug a hook in dev without editing eve’s code.

**Comment by sebest** [comment]
Yeah i think that even if we improve logging for 0.7 having a log for base Exception is mandatory today.

**Comment by nicolaiarocci** [comment]
See http://python-eve.org/features#enhanced-logging

**Comment by rs** [comment]
👍

**Pull request merged**
