### PR TITLE
Fix resource discovery in Mongo layer

### PR DESCRIPTION
**Pull request by amagdas**
Mongo layer should not depend on request context if possible, resource can be passed as a parameter.

### CODE REVIEW

**Comment by amagdas** [comment]
@nicolaiarocci is there a relative date when the release of Eve 0.6 will happen?

**Comment by nicolaiarocci** [comment]
This month.

**Comment by gmauleon** [comment]
I believe this will also fix oplog_push taking the current endpoint resource instead of the oplog one for mongo prefixes

**Comment by nicolaiarocci** [comment]
thanks!

**Pull request merged**
