### PR TITLE
better locating of settings.py

### PR DESCRIPTION
**Pull request by bomb-on**
First of all, sorry for putting this issue on the table again, but it seems that this is still not completely solved. Instead there are some very simple workarounds but I would like to see Eve even smarter than those workarounds (or at least properly documented issue), so here are my 2 cents...

# The Problem
I've been reading #137, #209, #713, #820, #918 (and others), along with issues related to this specific problem in [eve-sqlalchemy](https://github.com/RedTurtle/eve-sqlalchemy). Although some of those issues are outdated because they were related to older Eve versions, it seems that there are some isolated cases where this is still occurring.
In my case, I have a `settings.py` file in the root of my project, along with `application.py` where Eve is running. The application itself works fine in my local dev environment (OS X 10.12 with Python 3.5.1) and also when deploying it on AWS (AWS linux with Python 3.4) but I have a problem when I try to run tests with `py.test` on any platform because `settings.py` is never properly discovered.
We know already that the problem lies in [`load_config`](https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L202) method, specifically few lines which are responsible for locating `settings.py` file:
```
if isinstance(self.settings, dict):
    self.config.update(self.settings)
else:
    if os.path.isabs(self.settings):
        pyfile = self.settings
    else:
        abspath = os.path.abspath(os.path.dirname(sys.argv[0]))  # <-- this!
        pyfile = os.path.join(abspath, self.settings)
    try:
        self.config.from_pyfile(pyfile)
    except IOError:
        # assume envvar is going to be used exclusively
        pass  # <--- why pass? what if envvar is not used in the end??
    except:
        raise
```
which in my case results with either `pytest` binary (`/Users/oxxo/.virtualenvs/evetest/bin/pytest`), or if I try to run it in PyCharm with its `helpers` folder (`/Applications/PyCharm.app/Contents/helpers/pycharm`).

# Proposed Solutions
There are already few possible (and very simple) solutions to this, but I think it might be difficult to other people to figure it out without actually searching the repository's issues, so my suggestions are:

- remove the "magic" behind discovering `settings.py` completely and "force" explicitly passing settings to Eve constructor, either as a dictionary or as an absolute path to `settings.py`. (IMHO, this would be the worst solution :))
- just raise a proper exception instead of `ConfigException('DOMAIN dictionary missing or wrong.')`. Seems like this is what others are tripping over the most. There was some mentioning of this in #713, but to me it looks like this is still not solved completely.
- improve the method of locating `settings.py`. This would keep Eve's "magic" on the track and in my opinion this is the best solution, therefore I went in that direction and it resulted with this pull request :)

Anyhow, no matter which solution will be applied, it should be **properly documented**, at least to avoid future tripping over :)

Thanks a lot for this great framework, keep up with good work and thanks a lot for your time! :)

### CODE REVIEW

**Comment by bomb-on** [comment]
There are also 2 tiny additions to `.gitignore` and I fixed the typo in [`test_create_indexes()`](https://github.com/nicolaiarocci/eve/blob/develop/eve/tests/config.py#L490) which solves #960.

**Comment by bomb-on** [comment]
Eh, well, seems that tests are failing when running with `tox` because tests folder is not in `sys.path` after all (as I thought)... Will try to figure this out and update PR...

**Comment by nicolaiarocci** [comment]
I like the general approach you are taking here. Ayuto-magically figuring out a file path, however, is probably not so naive as it might seem at first glance.

**Comment by bomb-on** [comment]
Indeed :)
Straight out of the head, we might add the path manually just for this test case if you agree, or I can try to figure out a bit "smarter" way to find the file in this particular case.
I'll try to play around with it a bit more and hopefully propose "fully" working solution :)

**Comment by bomb-on** [comment]
So, this is passing now. I haven't test it on Windows because I have no Windows machine. Also, sorry for multiple commits :)

**Comment by dkellner** [comment]
@bomb-on You could use `git rebase --interactive ...` to squash those multiple commits together and make the history nicer before Nicola will merge this :).

**Comment by bomb-on** [comment]
@dkellner Oh, rebase? Damn, I did it once in my life and I have to admit that it didn't end up well :) But shouldn't this end up as a single commit after merging since my branch won't exist in this repo? Sorry, but I am still a bit noob-ish with git :)

About the documentation... Sure I could update it but I intentionally left it to @nicolaiarocci because I believe he knows the best what's happening behind the scenes and to transform it into human-readable sentence :)

**Comment by nicolaiarocci** [comment]
@bomb-on you should update the docs too. Just need to update the [source rst file](https://github.com/nicolaiarocci/eve/blob/develop/docs/config.rst). After that is done, I will rebase and merge for you.

**Comment by bomb-on** [comment]
@nicolaiarocci No probs! I'll try to do it sometimes today!

**Comment by bomb-on** [comment]
@nicolaiarocci This is done. As usual, I tend to overcomplicate even the simplest explanations, so if that is a case here too, please let me know and I'll try to reformulate some of the stuff :)

**Comment by nicolaiarocci** [comment]
Merged after rebase (see https://github.com/nicolaiarocci/eve/commit/d57176a7a9ec9068b59094b1b1e786723d667904)

Thanks!

**Pull request closed without merging**
