### PR TITLE
Cors allow credentials

### PR DESCRIPTION
**Pull request by cyppan**
ref #584

### CODE REVIEW

**Comment by cyppan** [comment]
I need help on this one...

**Comment by nicolaiarocci** [comment]
All green now :smiling_imp:

**Comment by cyppan** [comment]
magic...?

**Comment by nicolaiarocci** [comment]
Thanks!

**Comment by nicolaiarocci** [comment]
PS: the CI failure... we have a couple of Heisenbugs that show up from time to time. Usually I just need to relaunch the CI job.

**Comment by cyppan** [comment]
Ok for the Heisenbugs ^^! Thank you, glad to have contributed :)

**Pull request merged**
