### PR TITLE
Fix item_lookup_field for versioned resources

### PR DESCRIPTION
**Pull request by otibsa**
See #524.

I don't know how the tests for this need to be implemented.
Would be great, if I could get some help there.

What I tested manually:
```python
...
VERSIONING = True
ITEM_URL = 'regex("[a-z0-9]{0,24}")'
DOMAIN = {
    'people' = {
        'item_lookup_field': 'lastname',
        'schema': {
            'firstname': {'type': 'string'},
            'lastname': {'type': 'string', 'required': True, 'unique': True}
        }
    }
}
```

```
GET /people/obama
GET /people/obama?version=1
GET /people/obama?version=diffs

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
@joshvillbrandt would be great if you could lend your hand here: versioning is your baby :smile:

**Comment by joshvillbrandt** [comment]
Ref #524.

**Comment by nicolaiarocci** [comment]
So what is the state of this PR at the time being? I think tests are still missing and we're still waiting on @joshvillbrandt code review, right?

**Comment by otibsa** [comment]
That was my understanding as well. As I said, I did some "manual" tests, but I don't know how to implement them in the testing suite.

**Pull request closed without merging**
