### PR TITLE
Fix notifications example

### PR DESCRIPTION
**Pull request by stasfilin**
The last version is incorrect, in this version I use mongo for example and create a simple scheme for test table.
I think we need update, 'cause when I start to learn Eve first - I start example and example doesn't work, and I've been confused

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Hello, thanks for this. What exactly was the problem that you experienced? I just ran the notifications example without issues (send a GET request to `localhost:5000`).

**Comment by stasfilin** [comment]
@nicolaiarocci When i start example (not my) i got error; Need DOMAIN

**Comment by nicolaiarocci** [comment]
Ah, right. I stupidly ran it with a settings.py file in the local folder 😄

**Comment by stasfilin** [comment]
@nicolaiarocci yes, and if my example okay i can change all examples

**Comment by nicolaiarocci** [comment]
I merged after a rebase (see https://github.com/nicolaiarocci/eve/commit/68c242a1e50ba02d6a58e38b854ff96f245a3a31). Also I added some minor refactoring/cleanup. Thanks!

**Comment by stasfilin** [comment]
@nicolaiarocci so, I need to change another examples?

**Comment by nicolaiarocci** [comment]
yes please

**Pull request closed without merging**
