### PR TITLE
create_index add indexes to the versions collection

### PR DESCRIPTION
**Pull request by kalbasit**
`create_index` currently add indexes only for the resource but we also require indexes on the resource`_versions` which is created if versioning is enabled.

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Hey thanks for this, really needed. 

Would you refactor it a little bit, for increased DRY. [These lines](https://github.com/kalbasit/eve/blob/create_indexes_for_version_collection/eve/io/mongo/mongo.py#L931-L944) could go into a function or closure, so they can be invoked twice instead of repeating them for both standard and versioned collection.

**Comment by pfreixes** [comment]
Now these lines [1] need to become a closure.
@nicolaiarocci +1 

[1] https://github.com/kalbasit/eve/blob/create_indexes_for_version_collection/eve/io/mongo/mongo.py#L931-L944

**Comment by kalbasit** [comment]
PTAL

**Comment by nicolaiarocci** [comment]
Excellent. Thank you.

**Pull request merged**
