### PR TITLE
Get support to ignore some fields to compute the ETag value refs. #555

### PR DESCRIPTION
**Pull request by pfreixes**

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
You know what would be cool? Using dot notaion for neste dfields:

    ['field', 'dict.nested_field1']

Would make for a much more readable setting. What do you think?

**Comment by pfreixes** [comment]
If this makes the user life be easier obviously.

**Comment by nicolaiarocci** [comment]
I feel like it makes for a simpler notation (and dot notation is supported by json). Would you be willing to update the pr for this?

**Comment by pfreixes** [comment]
Oks no worries, let'me introduce this changes as a new commit of this pull request

**Comment by nicolaiarocci** [comment]
Merged to `develop`, planned to be released with v0.6. Thanks!

Please PR from a feature branch and not from your `develop` next time. Makes auto-closing of PRs easier.

**Pull request closed without merging**
