### PR TITLE
#749 bump versions of pymongo and flask-pymongo to enable (py)mongo 3 support

### PR DESCRIPTION
**Pull request by g----**
Bumped requirements version for pymongo3 support.

Are we ready to merge pymongo3 to master?

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Ah nice it was about time they released it :) 

Right now however there are performance issues with the test suite. I hope to have time to look at them soon, and I'm  not sure  the issue is on eve side actually, something fishy might be going on with latest Flask-PyMongo release. I updated the pymongo3 branch if you or somebody else wants to investigate it further.

**Comment by nicolaiarocci** [comment]
Ok I found the culprit. There are performance issues with PyMongo 3.0.x and Python 2.x. They have been fixed in PyMongo 3.1 which is not available yet so we'll have to wait until that one is released. For details see https://github.com/nicolaiarocci/eve/commit/b25bdf31b57bf5360fec543b9ccb4a20534750b4

**Comment by g----** [comment]
Ok, let's wait for pymongo 3.1 then.

Thanks for investigating!

**Comment by nicolaiarocci** [comment]
Support for PyMongo 3 is now merged to Eve-dev.

**Pull request closed without merging**
