### PR TITLE
FIX: Validate resource fields submitted as multipart/form-data

### PR DESCRIPTION
**Pull request by stratosgear**
Scratching my own #806 itch

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Cool stuff. 

1. Tests are failing
2. Wouldn't it be nice if this feature would kick in automatically when an endpoint has `media` type files in its schema? Just an idea, have not looked into it at all, but at first sight I don't see why one would want to be capable of only parsing string types.

**Comment by stratosgear** [comment]
I know about the failing tests. I'm having troubles bringing a 2.6 python env up to test why they fail just on 2.6, but pass on all others.

Unfortunately, I do not know how to make the process automatic, as you suggest.  I also agree that it doesn't make sense to have a resource full of strings.  You would still need to validate your resource even when you upload media.

The problem is with parsing the incoming form fields. As long as the incoming fields are properly formatted json structures everything is OK. Except if one wants to pass an actual string, in which case they **will have to enclose it in double quotes**, something that is not so obvious. The way the functionality is implemented is to parse all incoming form fields as JSON strings, a process where any random string (unless doubly quoted) fails. 

Not notifying the user and turning this feature on, will break backwards compatibility because no one encloses strings in double quotes by default

Kinda hard to explain....  Maybe someone else, smarter than me can step up, but I do not see any "transparent" way of handling it.  That's why I tried to implement it as an optional feature with a warning on how to properly deal with strings.

Do you have an issue label, labeled "Help Required" or something, so maybe more people might take a look?

**Comment by nicolaiarocci** [comment]
Howdy. I fixed the Py26 issue, reabased and merged with https://github.com/nicolaiarocci/eve/commit/c8a3fdfb39e4ab41fc4a055cce21fcb5f686085b

Thanks!

**Comment by nicolaiarocci** [comment]
PS: please double-check that I got the string syntax right while editing your documentation changes (http://python-eve.org/features.html#file-storage). If  not, please PR a fix.

**Pull request closed without merging**
