### PR TITLE
Fix regression for on_updated

### PR DESCRIPTION
**Pull request by amagdas**

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
This was actually intended. See https://github.com/nicolaiarocci/eve/blob/develop/CHANGES#L23-L24.

**Comment by amagdas** [comment]
I know but it looks like a regression... What it the actual use case for it? If you get only the payload, you can easily obtain the 'updated' as the 'original' is passed as well.

**Comment by amagdas** [comment]
The build is passing, the rate limit heisenbug is doing it's work.

**Comment by petrjasek** [comment]
it allows you to modify the response, we use that somewhere (i think with dictionaries)

**Comment by nicolaiarocci** [comment]
Also see discussion at #682

**Comment by amagdas** [comment]
My fix it's actually fixing #682 , we had this fix in our fork for quite some time, didn't manage to create a proper PR for it though :(

**Comment by amagdas** [comment]
Basically this PR is consistent, meaning you can still easily know what the payload is when calling 'on_updated' and changes to 'updates' will be reflected in the response.

**Comment by nicolaiarocci** [comment]
oh right, I didn't notice the final update call.

**Comment by amagdas** [comment]
So is this a proper fix?

**Comment by nicolaiarocci** [comment]
Yes. Merged with https://github.com/nicolaiarocci/eve/commit/43dfe08d6008114a19628ef7d6f18652ba401afb

Thank you!

**Pull request closed without merging**
