### PR TITLE
Allow posting lists by using the same key multiple times

### PR DESCRIPTION
**Pull request by Leonidaz0r**
HTTP allows multiple values with the same key in
application/x-www-form-urlencoded and multipart/form-data content types. We can
use this feature to send a list using for example an HTML form. This is very
useful to send a list of files.

This commit adds a config setting `AUTO_COLLAPSE_MULTI_KEYS` to enable automatic
conversion of data, which has the same key, to a list of values.

See issue #932

### CODE REVIEW

**Comment by Leonidaz0r** [comment]
The failing test is not because of this commit. See Issue #934.

**Comment by Leonidaz0r** [comment]
Ok travis seems to have run the tests again, now the tests are fine. Pushed a fix anyway, see the issue and my other pull request.

**Comment by nam4dev** [comment]
Great! I quite busy these days, but I'll check this ASAP

**Comment by Leonidaz0r** [comment]
Is this sufficient?

**Comment by nicolaiarocci** [comment]
Merged after rebase, see https://github.com/nicolaiarocci/eve/commit/12cf8e3d910d16a8026d1d116b232866d3f9bd55

Thanks.

**Pull request closed without merging**
